#Nombre de la aplicación
spring:
  application:
    name: "api-server"   

server:     
  port: 8080

eureka:        
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${URL_EUREKA_SERVER:http://localhost:8761/eureka}
    lease:
      duration: 5