spring:
  application:
    name: "remote-service-1"   

server:    
  port: 8090

eureka:        
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${URL_EUREKA_SERVER:http://localhost:8761/eureka}
    lease:
      duration: 5